# Generated by Django 4.1.5 on 2023-02-02 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmaceutical_care', models.CharField(max_length=225)),
                ('pharmaceutical_details', models.CharField(max_length=225)),
                ('proposed_intervention', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Interventions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmaceutical_care', models.CharField(max_length=225)),
                ('pharmaceutical_details', models.CharField(max_length=225)),
                ('medication', models.CharField(max_length=225)),
                ('proposed_intervention', models.CharField(max_length=225)),
                ('details', models.TextField(max_length=1000)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_interventions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
