# Generated by Django 4.1.5 on 2023-02-03 20:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("interventions", "0003_patients_gender_alter_patients_age_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InterventionResponses",
        ),
        migrations.DeleteModel(
            name="Medications",
        ),
    ]
