# Generated by Django 4.1.5 on 2023-06-19 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interventions", "0004_delete_interventionresponses_delete_medications"),
    ]

    operations = [
        migrations.AddField(
            model_name="interventions",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="interventions",
            name="updated_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 6, 19, 0, 22, 12, 474781, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patients",
            name="created_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="patients",
            name="updated_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 6, 19, 0, 22, 24, 208987, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
