# Generated by Django 4.1.5 on 2023-06-19 01:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interventions", "0005_interventions_created_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pharmaceutical_care", models.CharField(max_length=225)),
                ("pharmaceutical_details", models.CharField(max_length=225)),
                ("medication", models.CharField(max_length=225)),
                ("proposed_intervention", models.CharField(max_length=225)),
                ("details", models.TextField(blank=True, max_length=1000, null=True)),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("updated_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Interventions",
                "ordering": ["-created_date"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=225, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Rather not say", "Rather not say"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("weight", models.IntegerField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "further_details",
                    models.TextField(blank=True, max_length=225, null=True),
                ),
                ("created_date", models.DateTimeField(auto_now=True)),
                ("updated_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounts_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Interventions",
        ),
        migrations.DeleteModel(
            name="Patients",
        ),
        migrations.AddField(
            model_name="intervention",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="interventions.patient",
            ),
        ),
    ]
