# Generated by Django 4.1.5 on 2023-06-19 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interventions", "0006_intervention_patient_delete_interventions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="intervention",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts_interventions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
