# Generated by Django 4.1.5 on 2023-06-23 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interventions", "0007_intervention_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="patient",
            name="last_name",
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
