# Generated by Django 4.1.5 on 2023-02-02 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_student_id_alter_profile_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='account',
        ),
        migrations.AddField(
            model_name='employer',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_work_details', to='accounts.profile'),
        ),
    ]
