# Generated by Django 4.1.5 on 2023-02-03 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_delete_employer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place_of_work", models.CharField(max_length=100)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("Hospital", "Hospital"), ("Community", "Community")],
                        max_length=50,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_work_details",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
    ]
